#!/bin/bash

#c++ -std=c++11 -stdlib=libc++ -Iinclude -O2 main.cpp
c++ -std=c++11 -stdlib=libc++ -Iinclude -O2 -march=native main2.cpp
#g++-6 -Iinclude -O2 -march=native -fopenmp main2.cpp
#g++-6 -Iinclude -O2 -march=native main2.cpp
